const KEY="pobs_v1";
const seed={products:[
{id:1,name:"iPhone 13 128GB",sku:"IP13-128",category:"Phones",cost:18000,price:21500,stock:4,min:1},
{id:2,name:"Samsung A55",sku:"SA55",category:"Phones",cost:16500,price:19500,stock:7,min:2},
{id:3,name:"Bluetooth Speaker",sku:"BTS-01",category:"Accessories",cost:850,price:1299,stock:18,min:5},
{id:4,name:"Wireless Earbuds",sku:"EAR-01",category:"Accessories",cost:450,price:799,stock:3,min:5},
{id:5,name:"Smart TV 43\"",sku:"TV43",category:"Appliances",cost:12000,price:14999,stock:2,min:1}
],sales:[],purchases:[],customers:[],suppliers:[],expenses:[],nextId:100};
let db=JSON.parse(localStorage.getItem(KEY)||"null")||seed;
const money=n=>"₱"+Number(n||0).toLocaleString("en-PH",{minimumFractionDigits:2,maximumFractionDigits:2});
const save=()=>localStorage.setItem(KEY,JSON.stringify(db));
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function toast(s){const t=document.querySelector("#toast");t.textContent=s;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}
function daysAgo(d){return (Date.now()-new Date(d).getTime())/86400000}
function totals(){let sales=db.sales.reduce((a,x)=>a+x.total,0), buys=db.purchases.reduce((a,x)=>a+x.total,0), expenses=db.expenses.reduce((a,x)=>a+x.amount,0);return {sales,buys,expenses,profit:sales-db.sales.reduce((a,x)=>a+x.costTotal,0)-expenses}}
function render(page="dashboard"){
document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.page===page));
const titles={dashboard:["Dashboard","Your business at a glance"],sell:["Sell","Create a sales transaction"],buy:["Buy","Record products purchased from suppliers"],products:["Products","Manage your product catalog"],inventory:["Inventory","Track stock and stock movement"],customers:["Customers","Manage your buyers"],suppliers:["Suppliers","Manage your sources"],reports:["Reports","Sales, purchases and profitability"],settings:["Settings","Application preferences"]};
document.querySelector("#pageTitle").textContent=titles[page][0];document.querySelector("#pageSubtitle").textContent=titles[page][1];
document.querySelector("#content").innerHTML=views[page]();
if(page==="sell") initSell(); if(page==="buy") initBuy();
}
const views={
dashboard(){const t=totals(),low=db.products.filter(p=>p.stock<=p.min);return `<div class="grid stats">
<div class="card"><div class="stat-label">Today's Sales</div><div class="stat-value">${money(db.sales.filter(x=>new Date(x.date).toDateString()===new Date().toDateString()).reduce((a,x)=>a+x.total,0))}</div><div class="stat-note">${db.sales.length} total transactions</div></div>
<div class="card"><div class="stat-label">Total Purchases</div><div class="stat-value">${money(t.buys)}</div><div class="stat-note">Inventory investment</div></div>
<div class="card"><div class="stat-label">Gross Profit</div><div class="stat-value">${money(t.profit)}</div><div class="stat-note">After recorded expenses</div></div>
<div class="card"><div class="stat-label">Inventory Value</div><div class="stat-value">${money(db.products.reduce((a,p)=>a+p.cost*p.stock,0))}</div><div class="stat-note">${db.products.length} products</div></div>
</div>
<div class="grid two"><div class="card"><div class="section-head"><h2>Recent Sales</h2><button class="btn light" onclick="render('sell')">New Sale</button></div>${db.sales.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>Customer</th><th>Items</th><th>Total</th><th>Profit</th></tr></thead><tbody>${db.sales.slice(-6).reverse().map(s=>`<tr><td>${new Date(s.date).toLocaleDateString()}</td><td>${esc(s.customer||"Walk-in")}</td><td>${s.items.reduce((a,i)=>a+i.qty,0)}</td><td>${money(s.total)}</td><td>${money(s.total-s.costTotal)}</td></tr>`).join("")}</tbody></table></div>`:`<div class="empty">No sales yet. Start your first sale.</div>`}</div>
<div class="card"><div class="section-head"><h2>Low Stock</h2><button class="btn light" onclick="render('buy')">Buy Stock</button></div>${low.length?low.map(p=>`<div class="cart-line"><span>${esc(p.name)}<br><small>${p.stock} left</small></span><span class="badge ${p.stock===0?"out":"low"}">${p.stock===0?"OUT":"LOW"}</span></div>`).join(""):`<div class="empty">All products have healthy stock.</div>`}</div></div>`},
sell(){return `<div class="sale-layout"><div class="card"><div class="section-head"><h2>Choose Product</h2><input class="field input search" id="sellSearch" placeholder="Search products..." oninput="filterSell()"></div><div id="productPicker" class="product-picker"></div></div><div class="card"><div class="section-head"><h2>Current Sale</h2><button class="outline" onclick="clearCart()">Clear</button></div><div class="field"><label>Customer</label><input id="saleCustomer" placeholder="Walk-in customer"></div><div id="cart" style="margin-top:12px"></div><div class="total"><span>Total</span><span id="cartTotal">₱0.00</span></div><div class="actions"><button class="btn gold" onclick="completeSale()">Complete Sale</button></div></div></div>`},
buy(){return `<div class="card"><div class="section-head"><h2>New Purchase</h2><span class="badge">Stock IN</span></div><div class="form-grid"><div class="field"><label>Supplier</label><input id="buySupplier" placeholder="Supplier name"></div><div class="field"><label>Reference / Invoice</label><input id="buyRef" placeholder="Optional"></div><div class="field"><label>Product</label><select id="buyProduct">${db.products.map(p=>`<option value="${p.id}">${esc(p.name)} — current ${p.stock}</option>`).join("")}</select></div><div class="field"><label>Quantity</label><input id="buyQty" type="number" min="1" value="1"></div><div class="field"><label>Purchase Cost / Unit</label><input id="buyCost" type="number" step=".01"></div><div class="field"><label>Payment Method</label><select id="buyPayment"><option>Cash</option><option>GCash</option><option>Bank Transfer</option><option>Credit</option></select></div></div><div class="actions"><button class="btn" onclick="completeBuy()">Record Purchase</button></div></div>`},
products(){return `<div class="card"><div class="section-head"><h2>Product Catalog</h2><button class="btn" onclick="addProduct()">+ Add Product</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Product</th><th>SKU</th><th>Category</th><th>Cost</th><th>Sell Price</th><th>Stock</th><th>Status</th></tr></thead><tbody>${db.products.map(p=>`<tr><td><strong>${esc(p.name)}</strong></td><td>${esc(p.sku)}</td><td>${esc(p.category)}</td><td>${money(p.cost)}</td><td>${money(p.price)}</td><td>${p.stock}</td><td><span class="badge ${p.stock===0?"out":p.stock<=p.min?"low":""}">${p.stock===0?"Out":p.stock<=p.min?"Low":"In Stock"}</span></td></tr>`).join("")}</tbody></table></div></div>`},
inventory(){return `<div class="card"><div class="section-head"><h2>Inventory</h2><input class="field search" id="invSearch" placeholder="Search..." oninput="filterInventory()"></div><div class="table-wrap"><table class="table"><thead><tr><th>Product</th><th>SKU</th><th>Stock</th><th>Cost Value</th><th>Retail Value</th><th>Potential Profit</th></tr></thead><tbody id="invRows">${db.products.map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.sku)}</td><td>${p.stock}</td><td>${money(p.stock*p.cost)}</td><td>${money(p.stock*p.price)}</td><td>${money(p.stock*(p.price-p.cost))}</td></tr>`).join("")}</tbody></table></div></div>`},
customers(){return simpleDirectory("Customers","Customer",db.customers,"customer")},
suppliers(){return simpleDirectory("Suppliers","Supplier",db.suppliers,"supplier")},
reports(){const t=totals();let byProduct={};db.sales.forEach(s=>s.items.forEach(i=>{byProduct[i.name]=(byProduct[i.name]||0)+i.qty}));return `<div class="grid stats"><div class="card"><div class="stat-label">Sales Revenue</div><div class="stat-value">${money(t.sales)}</div></div><div class="card"><div class="stat-label">Purchases</div><div class="stat-value">${money(t.buys)}</div></div><div class="card"><div class="stat-label">Expenses</div><div class="stat-value">${money(t.expenses)}</div></div><div class="card"><div class="stat-label">Net Profit</div><div class="stat-value">${money(t.profit)}</div></div></div><div class="card" style="margin-top:18px"><div class="section-head"><h2>Top Products Sold</h2></div>${Object.keys(byProduct).length?Object.entries(byProduct).sort((a,b)=>b[1]-a[1]).map(([n,q])=>`<div class="cart-line"><span>${esc(n)}</span><strong>${q} sold</strong></div>`).join(""):`<div class="empty">Complete sales to generate reports.</div>`}</div>`},
settings(){return `<div class="card"><div class="section-head"><h2>Settings</h2></div><p style="color:var(--muted)">Points of Buy & Sell v1. Local-first demo data is stored in this browser.</p><div class="actions"><button class="btn danger" onclick="resetDemo()">Reset all demo data</button></div></div>`}
};
function simpleDirectory(title,label,arr,type){return `<div class="card"><div class="section-head"><h2>${title}</h2><button class="btn" onclick="addDirectory('${type}','${label}')">+ Add ${label}</button></div>${arr.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Name</th><th>Phone</th><th>Email</th></tr></thead><tbody>${arr.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.phone||"")}</td><td>${esc(x.email||"")}</td></tr>`).join("")}</tbody></table></div>`:`<div class="empty">No ${title.toLowerCase()} added yet.</div>`}</div>`}
let cart=[];
function initSell(){drawProducts(db.products);drawCart()}
function drawProducts(list){const el=document.querySelector("#productPicker");if(!el)return;el.innerHTML=list.map(p=>`<button class="product-tile" onclick="addToCart(${p.id})" ${p.stock<=0?"disabled":""}><strong>${esc(p.name)}</strong><small>${money(p.price)} · ${p.stock} in stock</small></button>`).join("")||`<div class="empty">No products found.</div>`}
function filterSell(){const q=document.querySelector("#sellSearch").value.toLowerCase();drawProducts(db.products.filter(p=>(p.name+" "+p.sku+" "+p.category).toLowerCase().includes(q)))}
function addToCart(id){const p=db.products.find(x=>x.id===id),c=cart.find(x=>x.id===id);if(!p)return;if(c){if(c.qty>=p.stock)return toast("Not enough stock");c.qty++}else cart.push({id,qty:1});drawCart()}
function drawCart(){const el=document.querySelector("#cart");if(!el)return;el.innerHTML=cart.length?cart.map(c=>{const p=db.products.find(x=>x.id===c.id);return `<div class="cart-line"><span>${esc(p.name)} × ${c.qty}<br><small>${money(p.price)} each</small></span><span><strong>${money(p.price*c.qty)}</strong><br><button class="outline" onclick="removeCart(${p.id})">remove</button></span></div>`}).join(""):`<div class="empty">Your cart is empty.</div>`;const total=cart.reduce((a,c)=>{let p=db.products.find(x=>x.id===c.id);return a+p.price*c.qty},0);document.querySelector("#cartTotal").textContent=money(total)}
function removeCart(id){cart=cart.filter(x=>x.id!==id);drawCart()}function clearCart(){cart=[];drawCart()}
function completeSale(){if(!cart.length)return toast("Add a product first");for(const c of cart){const p=db.products.find(x=>x.id===c.id);if(c.qty>p.stock)return toast("Insufficient stock for "+p.name)}let items=cart.map(c=>{const p=db.products.find(x=>x.id===c.id);p.stock-=c.qty;return {id:p.id,name:p.name,qty:c.qty,price:p.price,cost:p.cost}});let total=items.reduce((a,i)=>a+i.price*i.qty,0),costTotal=items.reduce((a,i)=>a+i.cost*i.qty,0);db.sales.push({id:db.nextId++,date:new Date().toISOString(),customer:document.querySelector("#saleCustomer").value||"Walk-in",items,total,costTotal});save();cart=[];toast("Sale completed");render("sell")}
function completeBuy(){const p=db.products.find(x=>x.id==+document.querySelector("#buyProduct").value),qty=+document.querySelector("#buyQty").value,cost=+document.querySelector("#buyCost").value||p.cost;if(!p||qty<1)return toast("Check purchase details");p.stock+=qty;p.cost=cost;db.purchases.push({id:db.nextId++,date:new Date().toISOString(),supplier:document.querySelector("#buySupplier").value||"Unknown",ref:document.querySelector("#buyRef").value,productId:p.id,qty,cost,total:qty*cost,payment:document.querySelector("#buyPayment").value});save();toast("Purchase recorded and stock updated");render("buy")}
function addProduct(){let name=prompt("Product name?");if(!name)return;let sku=prompt("SKU / barcode?")||("SKU-"+db.nextId),cost=+prompt("Purchase cost?","0")||0,price=+prompt("Selling price?","0")||0,stock=+prompt("Starting stock?","0")||0;db.products.push({id:db.nextId++,name,sku,category:"General",cost,price,stock,min:1});save();render("products");toast("Product added")}
function addDirectory(type,label){let name=prompt(label+" name?");if(!name)return;let phone=prompt("Phone?")||"",email=prompt("Email?")||"";db[type==="customer"?"customers":"suppliers"].push({id:db.nextId++,name,phone,email});save();render(type==="customer"?"customers":"suppliers");toast(label+" added")}
function filterInventory(){let q=document.querySelector("#invSearch").value.toLowerCase();document.querySelector("#invRows").innerHTML=db.products.filter(p=>(p.name+" "+p.sku).toLowerCase().includes(q)).map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.sku)}</td><td>${p.stock}</td><td>${money(p.stock*p.cost)}</td><td>${money(p.stock*p.price)}</td><td>${money(p.stock*(p.price-p.cost))}</td></tr>`).join("")}
function resetDemo(){if(confirm("Reset all Points of Buy & Sell demo data?")){localStorage.removeItem(KEY);location.reload()}}
document.querySelector("#nav").addEventListener("click",e=>{const b=e.target.closest(".nav-btn");if(b){document.querySelector(".sidebar").classList.remove("open");render(b.dataset.page)}})
document.querySelector("#menuBtn").onclick=()=>document.querySelector(".sidebar").classList.toggle("open");
document.querySelector("#today").textContent=new Date().toLocaleDateString("en-PH",{weekday:"short",year:"numeric",month:"short",day:"numeric"});
render();
